# Generated by Django 5.2.12 on 2026-04-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ['-data']},
        ),
    ]
